title="${filename}"

# OSD
#osd-blur=20
osd-font-size=32
osd-font='Arial'

# Equalizer
saturation=40
gamma=-10
contrast=-20

# Screenshot
screenshot-directory=C:\Users\prane\Pictures\Screenshots\mpv
screenshot-format=png
screenshot-png-compression=0

# Audio
volume-max=100
volume=70
